### ISSUE TITLE
How do I remove a sidebar?

### ISSUE THREAD

**Issue by Artuto** [MegavexNetwork/scoreboard-library#10]
I am trying to remove the scoreboard then a certain condition is met, however I cannot seem to figure out how to do this, or if it is a bug.

I've tried `close()`, `clearLines()` and removing the players but nothing seems to work. Is this intended?

**Comment by vytskalt** [comment]
.close() should remove it. What MC version are you using?

**Comment by Artuto** [comment]
1.20.4

**Comment by vytskalt** [comment]
`Sidebar#close()` correctly hides the sidebar for me with the `modern` packet adapter on version 2.0.1. Perhaps you are calling it on a different Sidebar instance?

**Comment by Artuto** [comment]
I am sure it is the same instance.

```
[17:06:41 INFO]: [STDOUT] Created net.craftium.libs.scoreboardlibrary.implementation.sidebar.SingleLocaleSidebar@6d3aa730
[17:06:52 INFO]: [STDOUT] Closed net.craftium.libs.scoreboardlibrary.implementation.sidebar.SingleLocaleSidebar@6d3aa730
```

And in-game looks like this (dont mind the unresolved placeholders):

![image](https://github.com/MegavexNetwork/scoreboard-library/assets/9273973/9d1b9e95-b3ce-40be-9225-fbd63feb4b00)

**Comment by Artuto** [comment]
It seems that calling close() when the plugin is being disabled (inside onDisable) causes this to occur. Is this expected?

**Comment by vytskalt** [comment]
> It seems that calling close() when the plugin is being disabled (inside onDisable) causes this to occur. Is this expected?

Yes, you also need to call ScoreboardLibrary#close in onDisable

**Comment by Artuto** [comment]
> > It seems that calling close() when the plugin is being disabled (inside onDisable) causes this to occur. Is this expected?
> 
> Yes, you also need to call ScoreboardLibrary#close in onDisable

That did it, thank you!
