### ISSUE TITLE
Scoreboard-library implementation is not shaded

### ISSUE THREAD

**Issue by Jakush** [MegavexNetwork/scoreboard-library#39]
Hey, I have this error:
Caused by: java.lang.IllegalStateException: scoreboard-library implementation is not shaded into the classpath

Though it should be normally shaded or?
This is my build.gradle and yes I have shadowJar there
```
implementation("net.megavex:scoreboard-library-api:2.1.8")
runtimeOnly("net.megavex:scoreboard-library-implementation:2.1.8")
runtimeOnly("net.megavex:scoreboard-library-modern:2.1.8")
```

**Comment by vytskalt** [comment]
do you have any custom shadowJar configuration? if so, please send it here

**Comment by vytskalt** [comment]
open the plugin .jar as a zip file and check if `net/megavex/scoreboardlibrary/implementation` exists

**Comment by vytskalt** [comment]
that looks like some sort of bug in ShadowJar, you can try changing `runtimeOnly` to `implementation` or switch to [this fork of ShadowJar](https://plugins.gradle.org/plugin/io.github.goooler.shadow) which is more up to date

**Comment by vytskalt** [comment]
you can still use minimize(), just need to exclude all scoreboard-library related dependencies

**Comment by vytskalt** [comment]
also add `exclude("net.megavex:scoreboard-library-commons")` and `exclude("net.megavex:scoreboard-library-packet-adapter-base")`

**Comment by vytskalt** [comment]
try removing the `:2.1.8` suffix

**Comment by vytskalt** [comment]
change `exclude("X")` to `exclude(dependency("X"))` like in the docs https://imperceptiblethoughts.com/shadow/configuration/minimizing/
