### ISSUE TITLE
Score on the right

### ISSUE THREAD

**Issue by justxdude** [MegavexNetwork/scoreboard-library#51]
Hi, 
Does the library delete the score on the right side of the scoreboard? 
![image](https://github.com/user-attachments/assets/8f1a5e5a-9f77-4b76-b296-c7c5b908c1da)

Thank you

**Comment by vytskalt** [comment]
It does, but only for 1.20.4+ clients. You can also set a custom value instead of a number.

**Comment by justxdude** [comment]
I'm using 1.21 so it's great for me. Thank you!
