### ISSUE TITLE
Allow for the max lines shown on the scoreboard to be greater than 15

### ISSUE THREAD

**Issue by Pigalala** [MegavexNetwork/scoreboard-library#7]
I noticed that MAX_LINES in Sidebar.java is set to 15, it would be cool to allow for values higher than 15.
I know that vanilla scoreboards have a limit of 15 entries but trust me yknow

**Comment by vytskalt** [comment]
You mean that you have a client that disables that vanilla restriction?

**Comment by Pigalala** [comment]
yes

**Comment by vytskalt** [comment]
Sure, I'll try to do it by today

**Comment by vytskalt** [comment]
@Pigalala set the version to `daa32239b9` and try creating the sidebar like this:
```java
Sidebar sidebar = scoreboardLibrary.createSidebar(/* maxLines = */ 20);
```
it should work with any number of max lines now
lmk if that works

**Comment by Pigalala** [comment]
perfect 
![image](https://github.com/MegavexNetwork/scoreboard-library/assets/73348859/21b31cb5-ed5e-4e15-9f16-38c24d3d52d0)

**Comment by vytskalt** [comment]
cool
